$font = Monospace

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 320px, 320px
    outline_thickness = 5
    inner_color = rgba(0, 0, 0, 0.4)
    outer_color = rgb(0, 0, 0) rgb(255, 0, 0) rgb(255, 215, 0) rgb(255, 0, 0) rgb(0, 0, 0) 120deg
    check_color = rgb(255, 215, 0) rgb(0, 0, 0) rgb(255, 215, 0) 120deg
    fail_color  = rgb(255, 0, 0) rgb(0, 0, 0) rgb(255, 0, 0) 120deg   # Neon red
	
	hide_input_base_color = rgba(0, 0, 0, 0)

    font_color = rgb(255, 215, 0)
    fade_on_empty = false
    rounding = -1

    font_family = $font
    placeholder_text =
    fail_text =

    hide_input = true
    dots_size = 0.1
    dots_spacing = 0.1

    position = 0, 0
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 48
    font_family = $font
    color = rgb(255, 215, 0)

    position = 0, -30
    halign = center
    valign = center
}

# LOCKED
label {
    monitor =
    text = Locked
    font_size = 28
    font_family = $font
    color = rgb(255, 0, 0)

    position = 0, 50
    halign = center
    valign = center
}


